workflows:
  web-workflow:
    name: Web Workflow
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: fvm
  ios-workflow:
    name: Web Workflow
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: fvm
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.gangyistudios.flutterfireCookbooks
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
  android-workflow:
    name: Android Workflow
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: fvm
      android_signing:
        - android-keystore
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
