// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_rxGZ44hdQ-oxqGRkFRA7HFuC_t1or14',
    appId: '1:932244088655:web:09301c02edc1ec2805473a',
    messagingSenderId: '932244088655',
    projectId: 'flutterfire-cookbooks',
    authDomain: 'flutterfire-cookbooks.firebaseapp.com',
    storageBucket: 'flutterfire-cookbooks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJwPCIvyPOQ2fqdpwG5n0V7FdiZDwZb-k',
    appId: '1:932244088655:android:d7cab033ca8fdc0805473a',
    messagingSenderId: '932244088655',
    projectId: 'flutterfire-cookbooks',
    storageBucket: 'flutterfire-cookbooks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC80bzMHXA_ljTv5uEfXtE8Zp_txVvVm-U',
    appId: '1:932244088655:ios:340508f70ebb67b805473a',
    messagingSenderId: '932244088655',
    projectId: 'flutterfire-cookbooks',
    storageBucket: 'flutterfire-cookbooks.appspot.com',
    iosClientId: '932244088655-pc5vth2dec14d8078ieuabls7isnr9be.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireCookbooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC80bzMHXA_ljTv5uEfXtE8Zp_txVvVm-U',
    appId: '1:932244088655:ios:340508f70ebb67b805473a',
    messagingSenderId: '932244088655',
    projectId: 'flutterfire-cookbooks',
    storageBucket: 'flutterfire-cookbooks.appspot.com',
    iosClientId: '932244088655-pc5vth2dec14d8078ieuabls7isnr9be.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireCookbooks',
  );
}
